name = "evaluate"

[preprocess]
cpp.suffixes = ["F90", "f90"]
cpp.macros = ["_FPM"]

[library]
source-dir = "src"

[fortran]
implicit-external = true

[install]
library = false

[[test]]
name = "test"
source-dir = "tests"
main="main.f90"

[[example]]
name = "calc"
source-dir = "examples/calc"
main = "calc.f90"